-- ═══════════════════════════════════════════════════════════════════════
-- HAJI AHLI — full schema for a NEW, EMPTY Supabase project.
--
-- NOT a migration file. Generated by concatenating the three migrations
-- in supabase/migrations/ in timestamp order, wrapped in one transaction
-- so a failure anywhere leaves the database exactly as it started.
--
-- Paste the whole thing into the Supabase SQL Editor and Run.
-- Safe to run ONCE on an empty database. Do not run twice.
-- ═══════════════════════════════════════════════════════════════════════

BEGIN;

-- ───────────────────────────────────────────────────────────────────────
-- 20260804071943_e00ce530-17dc-4f8d-97f3-6ef04aa0321b.sql
-- ───────────────────────────────────────────────────────────────────────
CREATE TYPE public.app_role AS ENUM ('admin','staff');

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read their own roles" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role);
$$;

CREATE TYPE public.booking_status AS ENUM ('new','confirmed','completed','cancelled');

CREATE TABLE public.bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_name text NOT NULL,
  phone text NOT NULL,
  email text,
  service text NOT NULL,
  property_type text,
  emirate text NOT NULL,
  address text,
  booking_date date NOT NULL,
  time_slot text NOT NULL,
  notes text,
  status public.booking_status NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bookings TO authenticated;
GRANT ALL ON public.bookings TO service_role;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view bookings" ON public.bookings FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'staff'));
CREATE POLICY "Admins can update bookings" ON public.bookings FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'staff'));
CREATE POLICY "Admins can delete bookings" ON public.bookings FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(),'admin'));

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;
CREATE TRIGGER bookings_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX bookings_date_idx ON public.bookings (booking_date);

-- ───────────────────────────────────────────────────────────────────────
-- 20260804071955_c1021f19-b4f5-4a8e-87e3-0ad5a1483d47.sql
-- ───────────────────────────────────────────────────────────────────────
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;

-- ───────────────────────────────────────────────────────────────────────
-- 20260812120000_structured_bookings_and_notifications.sql
-- ───────────────────────────────────────────────────────────────────────
-- Structured booking data + a channel-agnostic notification outbox.
--
-- Motivation: the original `bookings` table stores the service as free text
-- and has nowhere to put the package, add-ons, duration or price. A future
-- WhatsApp Business Platform integration needs to read and write the same
-- booking records the website does, so the data has to be structured and the
-- delivery mechanism has to be separate from the booking itself.
--
-- Nothing here is WhatsApp-specific. `notifications` is an outbox that any
-- channel worker can drain; WhatsApp is simply one value of `channel`.

-- ── booking reference ───────────────────────────────────────────────────────
-- Short, human-quotable identifier. A customer reading it over the phone
-- should not have to spell a UUID, so it is HA-<6 alphanumerics>, generated
-- from an alphabet with no 0/O/1/I to avoid transcription errors.
CREATE OR REPLACE FUNCTION public.generate_booking_reference()
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  alphabet text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text := '';
  i integer;
BEGIN
  FOR i IN 1..6 LOOP
    result := result || substr(alphabet, floor(random() * length(alphabet) + 1)::int, 1);
  END LOOP;
  RETURN 'HA-' || result;
END;
$$;

ALTER TABLE public.bookings
  -- Customer-facing reference. Unique so it can be looked up directly.
  ADD COLUMN IF NOT EXISTS reference text UNIQUE DEFAULT public.generate_booking_reference(),

  -- Catalogue linkage. Text rather than FK because the catalogue lives in the
  -- repo (generated from the workbook), not in the database.
  ADD COLUMN IF NOT EXISTS service_id text,
  ADD COLUMN IF NOT EXISTS service_category text,
  ADD COLUMN IF NOT EXISTS variant_id text,

  -- What the customer chose about their property, which is what drives both
  -- price and duration for the whole-home packages.
  ADD COLUMN IF NOT EXISTS property_size text,
  ADD COLUMN IF NOT EXISTS furnishing text,

  -- Add-ons as structured JSON: [{ id, name, quantity }]. JSONB so a channel
  -- worker can query it without parsing the notes field.
  ADD COLUMN IF NOT EXISTS add_ons jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- Scheduling. `requested_start` is what the customer asked for;
  -- `estimated_minutes` is filled once duration metrics exist, and
  -- `scheduled_end` is derived from the two at confirmation time.
  ADD COLUMN IF NOT EXISTS requested_start time,
  ADD COLUMN IF NOT EXISTS estimated_minutes integer,
  ADD COLUMN IF NOT EXISTS scheduled_end timestamptz,

  -- Commercial fields. Null until pricing is finalised; payment is not wired
  -- up yet, but the columns exist so adding it is not a schema migration on
  -- live booking data.
  ADD COLUMN IF NOT EXISTS price_amount numeric(10, 2),
  ADD COLUMN IF NOT EXISTS price_currency text NOT NULL DEFAULT 'AED',
  ADD COLUMN IF NOT EXISTS payment_status text NOT NULL DEFAULT 'not_required',

  -- Where the booking came from, so WhatsApp-originated bookings are
  -- distinguishable from web ones in the same table.
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'web',
  -- Preferred channel for replies to this customer.
  ADD COLUMN IF NOT EXISTS preferred_channel text NOT NULL DEFAULT 'phone';

-- Backfill references for any rows created before this migration.
UPDATE public.bookings
   SET reference = public.generate_booking_reference()
 WHERE reference IS NULL;

ALTER TABLE public.bookings
  ADD CONSTRAINT bookings_payment_status_check
  CHECK (payment_status IN ('not_required', 'pending', 'paid', 'refunded', 'failed'));

ALTER TABLE public.bookings
  ADD CONSTRAINT bookings_source_check
  CHECK (source IN ('web', 'whatsapp', 'phone', 'admin'));

ALTER TABLE public.bookings
  ADD CONSTRAINT bookings_preferred_channel_check
  CHECK (preferred_channel IN ('phone', 'whatsapp', 'email'));

CREATE INDEX IF NOT EXISTS bookings_reference_idx ON public.bookings (reference);
CREATE INDEX IF NOT EXISTS bookings_service_id_idx ON public.bookings (service_id);
CREATE INDEX IF NOT EXISTS bookings_date_status_idx ON public.bookings (booking_date, status);

-- ── notification outbox ─────────────────────────────────────────────────────
-- Channel-agnostic. A worker for any channel selects its own pending rows,
-- delivers them, and records the outcome. The booking engine only ever
-- enqueues; it never knows how a message is sent.
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id uuid REFERENCES public.bookings (id) ON DELETE CASCADE,

  -- What happened, not how to say it. Templates live with the channel worker.
  event text NOT NULL CHECK (
    event IN (
      'booking_created',
      'booking_confirmed',
      'booking_status_changed',
      'booking_cancelled',
      'enquiry_received'
    )
  ),
  channel text NOT NULL CHECK (channel IN ('whatsapp', 'email', 'sms', 'internal')),
  -- 'customer' or 'staff' — the same event goes to both, worded differently.
  audience text NOT NULL DEFAULT 'customer' CHECK (audience IN ('customer', 'staff')),

  -- Denormalised so a delivery worker needs no join and a later change of
  -- customer phone number does not rewrite delivery history.
  recipient text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,

  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'sent', 'failed', 'skipped')),
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  -- Provider message id, for delivery-receipt reconciliation later.
  provider_message_id text,

  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz
);

CREATE INDEX IF NOT EXISTS notifications_pending_idx
  ON public.notifications (channel, status, created_at)
  WHERE status = 'pending';

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Only admins may read the outbox; it contains customer contact details.
CREATE POLICY "Admins can read notifications"
  ON public.notifications FOR SELECT
  USING (public.has_role(auth.uid(), 'admin'));

-- Rows are written by trusted server code (service role), which bypasses RLS.
-- No anon insert policy: a public client must never enqueue a message.

-- ───────────────────────────────────────────────────────────────────────
-- Record these as applied, so a future `supabase db push` does not try to
-- run them again against a database that already has them.
-- ───────────────────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS supabase_migrations;
CREATE TABLE IF NOT EXISTS supabase_migrations.schema_migrations (version text PRIMARY KEY);
INSERT INTO supabase_migrations.schema_migrations (version) VALUES
  ('20260804071943'),
  ('20260804071955'),
  ('20260812120000')
ON CONFLICT (version) DO NOTHING;

COMMIT;
